<?php

namespace App\Traits;



use Illuminate\Database\Eloquent\Builder;

trait SetearYFiltrarPorCompaniaId{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            if (auth()->check()) {
                $model->compania_id = auth()->user()->compania_id;
            }
        });

//        throw new \Exception("hola: " . auth()->id());

        self::addGlobalScope(function(Builder $builder){
            if (auth()->check()) {
                $builder->where("compania_id", auth()->user()->compania_id);
            }
        });
    }

}
