<?php
namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;

trait SetearUserYCompaniaIdYFiltrarPorCompania{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            if (auth()->check()) {
                $user = auth()->user();
                $model->user_id = $user->id;
                $model->compania_id = $user->compania_id;
            }
        });

        self::addGlobalScope(function (Builder $builder){
            if (auth()->check()) {
                $builder->where("compania_id", auth()->user()->compania_id);
            }
        });
    }
}
