<?php

namespace App\Models;

use App\Traits\SetearYFiltrarPorCompaniaId;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Query\Builder;

class Cuenta extends Model
{
    use HasFactory, SetearYFiltrarPorCompaniaId;

    protected $fillable = ["descripcion", "banco_id", "compania_id"];

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::creating(function($model){
//            $model->compania_id = auth()->compania_id;
//        });
//
//
//        self::addGlobalScope(function(Builder $builder){
//            throw new \Exception("hola: " . auth()->id());
//            $builder->where("compania_id", auth()->user()->compania_id);
//        });
////        self::addGlobalScope(function(Builder $builder){
////            $builder->where("compania_id", auth()->user()->compania_id);
//////            throw new \Exception("hola: " . auth()->id());
////        });
//    }

}
